spring:
  profiles:
    active: dev

#server:
#  port: 8080
#  context-path: /Girl
#
#Girl:
#  cupSize: F
#  age: 18


#content: "cupSize: ${cupSize},age: ${age}"

#prot: 后加空格

#server.port=8080
#server.context-path=/Girl




#
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/
#spring.datasource.username=admin
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver